### ISSUE TITLE
uploading over cellular

### ISSUE THREAD

**Issue by andrei4002** [etcetc/OBFileTransfer#1]
I'm having issues while uploading a file in the background, over cellular data (not wifi - over wifi works fine)

so basically if a transfer is started in the background, over cellular, it doesn't go through until you go to the foreground.

**Comment by etcetc** [comment]
I believe this is a limitation of Apple's background transfer services.  Per Apple documentation  @ https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLSessionConfiguration_class/#//apple_ref/occ/instp/NSURLSessionConfiguration/discretionary

"For transfers started while your app is in the background, the system always starts transfers at its discretion—in other words, the system assumes this property is YES and ignores any value you specified".  What this means is that ti will only transfer over WiFi if the system has adequate power.
